apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-test-ui-service
  name: security-test-ui-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: security-test-ui
  type: ClusterIP