apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csi-net-base-sms
  name: csi-net-base-sms
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-base-sms
  template:
    metadata:
      labels:
        app: csi-net-base-sms
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: 'harbor.cs.local/vidaplus/csi-net-base-sms:4.0.26.0'
          name: csi-net-base-sms
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-base-sms
  name: csi-net-base-sms
  namespace: csi-perf
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: csi-net-base-sms
  type: LoadBalancer

