apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-common-report-generator-java-sev
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-ehr-common-report-generator-java-sev
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-common-report-generator-java-sev
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: db-rep-url
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-rep-username
                  name: ehr-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-rep-password
                  name: ehr-database-secret
            - name: SPRING_DATASOURCE_driver_class_name
              valueFrom:
                configMapKeyRef:
                  key: db-driver
                  name: service-configs
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP-SERVERS
                  name: service-configs
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: hostname
              value: csi-java-ehr-common-report-generator
          image: >-
            harbor.cs.local/vidaplus/csi-ehr-common-report-generator-java-sev:4.0.7.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            timeoutSeconds: 10
          name: csi-ehr-common-report-generator-java-sev
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ehr-common-report-generator
  name: csi-java-ehr-common-report-generator
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-common-report-generator-java-sev
  type: ClusterIP

