apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-bm-approval-java-serviceg
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-bm-approval-java-service
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-bm-approval-java-service
        module: billing
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: active_profile
                  name: service-configs-bm
            - name: hostname
              value: csi-bm-approval
            - name: FEIGN_HYSTRIX_ENABLED
              value: 'false'
            - name: CSI_JPA_EVENT_ISREPORT
              value: 'false'
          envFrom:
            - configMapRef:
                name: service-configs
            - configMapRef:
                name: service-configs-bm
            - secretRef:
                name: service-configs-secret
            - secretRef:
                name: service-bm-secret
          image: >-
            harbor.cs.local/vidaplus/csi-bm-approval-java-service:4.3.114.0
          imagePullPolicy: IfNotPresent
          name: csi-bm-approval-java-service
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-bm-approval
  name: csi-bm-approval
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-bm-approval-java-service
  type: ClusterIP

