apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-ip
  namespace: csi-perf
spec:
  replicas: 5
  selector:
    matchLabels:
      app: csi-ehr-ip
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-ip
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: database-url
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-ip-username
                  name: ehr-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-ip-password
                  name: ehr-database-secret
            - name: SPRING_JPA_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-driver
                  name: service-configs
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: SPRING_JPA_HIBERNATE_DIALECT
                  name: service-configs
            - name: hostname
              value: csi-java-ehr-ip
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: 'harbor.cs.local/vidaplus/csi-ehr-ip-java-sev:4.0.399.3-beta'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            periodSeconds: 40
            timeoutSeconds: 30
          name: csi-ehr-ip
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 30
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ehr-ip
  name: csi-java-ehr-ip
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-ip
  type: ClusterIP

