apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-lab-labg-ui
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-lab-labg-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-lab-labg-ui
        module: lab
        tier: frontend
        track: stable
    spec:
      containers:
        - image: 'harbor.cs.local/vidaplus/lab-ui:4.1.118.0'
          imagePullPolicy: IfNotPresent
          name: csi-lab-labg-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-lab-labg-ui-service
  name: csi-lab-labg-ui-service
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-lab-labg-ui
  type: ClusterIP

