---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrcommonjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrcommonjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrconfigjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrconfigjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehricbundlejava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehricbundlejava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehricdashboardjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehricdashboardjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehricui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehricui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrintitialassessjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrintitialassessjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehripdashboardwiddotnet
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehripdashboardwiddotnet/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehripdischargedotnet
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehripdischargedotnet/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehripjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehripjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrldrjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrldrjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrlistnerjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrlistnerjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehropdjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehropdjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehropdmasterdotnet
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehropdmasterdotnet/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehropdpatientdotnet
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehropdpatientdotnet/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehropdui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehropdui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehroranesthesiajava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehroranesthesiajava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrorbookingjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrorbookingjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrorbookjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrorbookjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrpomrjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrpomrjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrreportgeneratorjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrreportgeneratorjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrschedulerjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrschedulerjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrspecializedclinicjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrspecializedclinicjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ehrtemplatejava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/ehrtemplatejava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-workflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: ehr/workflow/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD