apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-billingmasterui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/billingmasterui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bmapprovalui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/bmapprovalui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bmbillingapprovaljava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/bmbillingapprovaljava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bmbillinginvoicejava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/bmbillinginvoicejava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bmbillingjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/bmbillingjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bminvoiceui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: billing/bminvoiceui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD
