---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bloodbank-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: Bloodbank/bloodbank-backend/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bloodbank-ui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: Bloodbank/bloodbank-ui/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bloodbankjava
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: csi-dev
    server: https://172.15.100.13:6443
  project: csi.dev.cloudsol.lk
  source:
    path: Bloodbank/bloodbankjava/dev/
    repoURL: https://nathan.roshan@172.15.100.56/scm/ky/deployment.git
    targetRevision: HEAD