apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-noty-query
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-noty-query
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-noty-query
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-net-base-notifications-query:4.0.21.0
          name: csi-net-noty-query
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 750Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-noty-query
  name: csi-net-noty-query
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-noty-query
  type: ClusterIP

