apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-patient-snapshot-java-sev
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-patient-snapshot-java-sev
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-patient-snapshot-java-sev
        module: base
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: hostname
              value: csi-patient-snapshot
            - name: FEIGN_HYSTRIX_ENABLED
              value: 'false'
            - name: spring_cache_type
              value: none
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP-SERVERS
                  name: service-configs
          envFrom:
            - configMapRef:
                name: service-configs
            - configMapRef:
                name: service-configs-rcm
          image: >-
            harbor.cs.local/vidaplus/csi-patient-snapshot-java-sev:V1.0.1_PERF
          imagePullPolicy: IfNotPresent
          name: csi-patient-snapshot
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-patient-snapshot
  name: csi-patient-snapshot
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-patient-snapshot-java-sev
  type: ClusterIP

