apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-empiread
  namespace: csi-perf
spec:
  replicas: 6
  selector:
    matchLabels:
      app: csi-net-empiread
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-empiread
        module: empi
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-empi-patient-service-read:4.2.4.0
          name: csi-net-empiread
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-empiread
  name: csi-net-empiread
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-empiread
  type: ClusterIP

