apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-test-ui-service-2
  name: security-test-ui-service-2
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: security-test-ui-2
  type: ClusterIP