apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-noty-email
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-noty-email
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-noty-email
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: 'harbor.cs.local/vidaplus/csi-net-base-email:4.0.11.0'
          name: csi-net-noty-email
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-noty-email
  name: csi-net-noty-email
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-noty-email
  type: ClusterIP

