apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: net-ehr-ip-discharg
  namespace: csi-perf
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-net-ehr-ip-discharg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-ehr-ip-discharg
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-ehr-ip-discharg
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-ehr-ip-discharg
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-ehr-com-ip-discharge-dotnet-sev:4.0.9.0
          imagePullPolicy: IfNotPresent
          name: csi-net-ehr-ip-discharg
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 750Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-ehr-ip-discharg
  name: csi-net-ehr-ip-discharg
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-ehr-ip-discharg
  type: ClusterIP

