apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: csi-dev
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/test-ui
  newTag: master-v1.2.0.20-g6e799c8
