apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-storage-engine-service
  namespace: csi-perf
spec:
  replicas: 0
  selector:
    matchLabels:
      app: document-storage-engine-service
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: document-storage-engine-service
        module: dms
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: PROFILE
              value: prod
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: service-configs-dms
            - name: db_user
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: service-secret-dms
            - name: db_password
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: service-secret-dms
            - name: minio_endpoint
              valueFrom:
                configMapKeyRef:
                  key: minio_endpoint
                  name: service-configs-dms
            - name: minio_accessKey
              valueFrom:
                secretKeyRef:
                  key: minio_accessKey
                  name: service-secret-dms
            - name: minio_secretKey
              valueFrom:
                secretKeyRef:
                  key: minio_secretKey
                  name: service-secret-dms
            - name: kafka_bootstrap_servers
              valueFrom:
                configMapKeyRef:
                  key: CSI_LOGS_KAFKA_BOOTSTRAPADDRESS
                  name: service-configs
            - name: elk_log_topic
              valueFrom:
                configMapKeyRef:
                  key: CSI_LOGS_KAFKA_TOPIC
                  name: service-configs
            - name: CSI_ENV_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: CSI_ENV_PREFIX
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/document-management-engine:1.5.9
          imagePullPolicy: IfNotPresent
          name: document-storage-engine-service
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 2Gi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: document-storage-engine-service
  name: document-storage-engine-service
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: document-storage-engine-service
  type: ClusterIP

