apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-phr-base
  newTag: 4.0.22.99 #4.0.22.98 #4.0.22.97 #4.0.22.91 #4.0.22.83 #4.0.22.91 #4.0.22.83
