apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-phr-base
  newTag: 4.0.22.198 #4.0.22.199 #4.0.22.194 #4.0.22.193 #4.0.22.187
