apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-phr-base
  newTag: 4.0.22.204 #4.0.22.203 #4.0.22.201 #4.0.22.200 #4.0.22.199
