apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-java-ehr-or-book
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-java-ehr-or-book
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-java-ehr-or-book
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: database-url
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-or-book-username
                  name: ehr-database-secret
            - name: SPRING_JPA_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-or-book-password
                  name: ehr-database-secret
            - name: hostname
              value: csi-java-ehr-or-book
            - name: SPRING_jpa_properties_hibernate_temp_use_jdbc_metadata_defaults
              value: 'true'
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: >-
            harbor.cs.local/vidaplus/csi-ehr-or-book-java-sev:4.0.52.0
          imagePullPolicy: IfNotPresent
          name: csi-java-ehr-or-book
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ehr-or-book
  name: csi-java-ehr-or-book
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-java-ehr-or-book
  type: ClusterIP

