apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-labsrvcs
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-labsrvcs
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-labsrvcs
        module: lab
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: 'harbor.cs.local/vidaplus/lab-labmgt-srv:4.1.267.0'
          imagePullPolicy: IfNotPresent
          name: csi-net-labsrvcs
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 5Gi
            requests:
              cpu: 50m
              memory: 5Gi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-labsrvcs
  name: csi-net-labsrvcs
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-labsrvcs
  type: ClusterIP

